/*  Copyright 2011-2014 Theo Berkau

    This file is part of PseudoSaturn.

    PseudoSaturn is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    PseudoSaturn is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with PseudoSaturn; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
	char *array_name="array";
	FILE *fp;
	long size;
	unsigned char *buf;
	long i, j;

	if (argc < 3)
	{
		printf("BIN2C by Cyber Warrior X\n");
	   printf("usage: bin2c <source binary file> <destination source file> <optional array name>");
		exit(1);
	}

	if (argc > 3)
		array_name = argv[3];

	if ((fp = fopen(argv[1], "rb")) == NULL)
	{
		printf("Error opening %s", argv[1]);
		exit(1);
	}

    fseek(fp, 0, SEEK_END);
	size = ftell(fp);
    fseek(fp, 0, SEEK_SET);
	if ((buf = malloc(size)) == NULL)
	{

		printf("Error allocating buffer\n");
		fclose(fp);
		exit(1);
	}

	fread((void *)buf, 1, size, fp);
	fclose(fp);

	if ((fp = fopen(argv[2], "wt")) == NULL)
	{
		printf("Error opening %s for writing", argv[2]);
		exit(1);
	}

	fprintf(fp, "// Autogenerated by BIN2C by Cyber Warrior X. Modifications may be overwritten!\n"
		         "#include \"types.h\"\n"
		         "\n"
					"u8 %s[%d] = \n"
					"{\n",
					array_name, size);

	for (i = 0; i < size; i += 15)
	{
		int count;
		if ((i+15) <= size)
			count=15;
		else
			count=size-i;

		fprintf(fp, "\t");
		for (j = 0; j < count; j++)
         fprintf(fp, "0x%02X,", buf[i+j]);
	   fprintf(fp, "\n");
	}

	fprintf(fp, "};\n"
		         "\n"
					"u32 %s_size = sizeof(%s);\n",
		         array_name, array_name);

	fclose(fp);
}
